-- Pedidos de envío del marketplace (Compraventa). Tabla financiera: a propósito no sigue la
-- convención de "insert por dueño" del resto del repo — todas las escrituras las hacen las
-- Edge Functions con la service role key, porque los importes los calcula el servidor.
create table public.orders (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.marketplace_listings(id),
  buyer_id uuid not null,
  seller_id uuid not null,
  buyer_email text not null,
  seller_email text not null,
  item_price numeric not null,
  shipping_price numeric not null,
  platform_fee numeric not null,
  total_amount numeric not null,
  currency text not null default 'eur',
  delivery_address jsonb not null,
  status text not null default 'pendiente_pago'
    check (status in ('pendiente_pago','pendiente_envio','enviado','entregado','confirmado','cancelado')),
  stripe_payment_intent_id text,
  stripe_transfer_id text,
  packlink_shipment_id text,
  packlink_label_url text,
  packlink_tracking_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.orders enable row level security;

create index orders_listing_id_idx on public.orders (listing_id);
create index orders_buyer_id_idx on public.orders (buyer_id);
create index orders_seller_id_idx on public.orders (seller_id);
create index orders_status_idx on public.orders (status);

create policy "Buyer or seller can read their own orders"
  on public.orders for select
  using ((select auth.uid()) in (buyer_id, seller_id));
-- Sin policy de insert/update/delete para authenticated/anon: todo pasa por Edge Functions.
