-- Pestaña Empleabilidad (Servicios.jsx): tabla hermana de marketplace_listings / school_routes.
create table if not exists public.employability_listings (
  id bigint generated by default as identity primary key,
  listing_type text not null check (listing_type in ('oferta', 'busqueda')),
  category text not null check (category in ('educacion', 'bienestar', 'artes', 'retiros', 'salud')),
  title text not null,
  description text,
  author_email text not null,
  author_name text,
  author_avatar text,
  created_at timestamptz not null default now()
);

alter table public.employability_listings enable row level security;

create index if not exists employability_listings_author_email_idx
  on public.employability_listings (author_email);

create policy "Public read access"
  on public.employability_listings
  for select
  using (true);

create policy "Owners can insert their own listings"
  on public.employability_listings
  for insert
  with check ((select auth.jwt()) ->> 'email' = author_email);

create policy "Owners can update their own listings"
  on public.employability_listings
  for update
  using ((select auth.jwt()) ->> 'email' = author_email)
  with check ((select auth.jwt()) ->> 'email' = author_email);

create policy "Owners can delete their own listings"
  on public.employability_listings
  for delete
  using ((select auth.jwt()) ->> 'email' = author_email);
